clc;
clear all;
close all;
fs = 1000;
fm1 = input('Enter 1st Message Signal Frequency (30) : ');
fm2 =input('Enter 2nd Message Signal Frequency (60) : ');
fc = input('Enter Carrier Signal Frequency (200): ');  
t = (0:1/fs:0.2);
x = sin(2*pi*fm1*t)+2*sin(2*pi*fm2*t);
w = sin(2*pi*fc*t);
fDev = 50;
y = fmmod(x,fc,fs,fDev);
z = fmdemod(y,fc,fs,fDev);
subplot(5,1,1);
plot(t,x,'r');
title('Message Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(5,1,2);
plot(t,w,'g');
title('Carrier Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(5,1,3);
plot(t,y,'m');
title('Frequency Modulated Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(5,1,4);
plot(t,z,'b');
title('Frequency Demodulated Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(5,1,5);
plot(t,z,'b',t,x,'--r');
title('Comparing Message and Demodulated Signal');
xlabel('Time (s)');
ylabel('Amplitude');
legend('Demodulated Signal','Message Signal');
